### ISSUE TITLE
`ft-flow/enforce-suppression-code`: TypeError: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by mrtnzlml** [flow-typed/eslint-plugin-ft-flow#12]
Hola, I am trying to replace `eslint-plugin-flowtype` with `eslint-plugin-ft-flow` and there is a new rule `ft-flow/enforce-suppression-code`. Unfortunately, it fails in many files on our codebase with the following error:

```text
$ /Users/martinzlamal/Work/adeira/universe/node_modules/.bin/eslint src/sx-design/src/constants.js

Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError: Cannot read properties of undefined (reading 'startsWith')
Occurred while linting /Users/martinzlamal/Work/adeira/universe/src/sx-design/src/constants.js:19
    at /Users/martinzlamal/Work/adeira/universe/node_modules/eslint-plugin-ft-flow/dist/rules/enforceSuppressionCode.js:21:17
    at Array.forEach (<anonymous>)
    at isMissingSuppressionCode (/Users/martinzlamal/Work/adeira/universe/node_modules/eslint-plugin-ft-flow/dist/rules/enforceSuppressionCode.js:20:33)
    at handleComment (/Users/martinzlamal/Work/adeira/universe/node_modules/eslint-plugin-ft-flow/dist/rules/enforceSuppressionCode.js:32:24)
    at Array.forEach (<anonymous>)
    at Program (/Users/martinzlamal/Work/adeira/universe/node_modules/eslint-plugin-ft-flow/dist/rules/enforceSuppressionCode.js:41:119)
    at /Users/martinzlamal/Work/adeira/universe/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/martinzlamal/Work/adeira/universe/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/martinzlamal/Work/adeira/universe/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
```

The simplest file where this is happening is probably: https://github.com/adeira/universe/blob/02aa03c955c17ebb4a60d4f1f7ce65c19943f9ac/src/sx-design/src/constants.js (clone the repo and run `yarn eslint src/sx-design/src/constants.js` to reproduce)

Thanks for having a look! 😊

**Comment by mrtnzlml** [comment]
Related issue: https://github.com/adeira/universe/issues/3609

**Comment by Brianzchen** [comment]
Thanks managed to reproduce this, I'll see what I can do

**Comment by Brianzchen** [comment]
https://github.com/flow-typed/eslint-plugin-ft-flow/releases/tag/v1.0.2
Released here, let me know if there's anymore issues

**Comment by mrtnzlml** [comment]
I can confirm it works well now! https://github.com/adeira/universe/pull/3631
